version: '3.7'
services:
  database_microservice:
    build: .
    restart: unless-stopped
    ports:
      - 27016:27016
    environment:
      - DATABASE_ENDPOINT=http://host.docker.internal:27000

networks:
  beuthbot: {}
  default:
    external:
      name: beuthbot_network